### ISSUE TITLE
Suffix j-search is not defined or autoloaded as a command

### ISSUE THREAD

**Issue by NoahDragon** [jojojames/hydra-integrations#3]
Thanks for making emacs more efficient with this package.

However, I got this error message when setting it up based on the instruction in readme.org: "Suffix j-search is not defined or autoloaded as a command".

I didn't find any useful information about the j-search from Google. Could you please give me some hints on it?

**Comment by jojojames** [comment]
You can set matcha-me-p to nil before loading matcha so it doesn't load my personal config. (matcha-me.el)

I have a few functions I declare in my init that matcha uses too. Not sure yet if I wanna move it to matcha since I didn't really expect anyone to want to use the stuff in matcha-me.el. (Let me know if that's not a good assumption. :))
